/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchFlightRouteImport } from './routes/search-flight'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyBookingsIndexRouteImport } from './routes/my-bookings/index'
import { Route as MyBookingsBookingIdRouteImport } from './routes/my-bookings/$bookingId'

const SearchFlightRoute = SearchFlightRouteImport.update({
  id: '/search-flight',
  path: '/search-flight',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsIndexRoute = MyBookingsIndexRouteImport.update({
  id: '/my-bookings/',
  path: '/my-bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsBookingIdRoute = MyBookingsBookingIdRouteImport.update({
  id: '/my-bookings/$bookingId',
  path: '/my-bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search-flight': typeof SearchFlightRoute
  '/my-bookings/$bookingId': typeof MyBookingsBookingIdRoute
  '/my-bookings/': typeof MyBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search-flight': typeof SearchFlightRoute
  '/my-bookings/$bookingId': typeof MyBookingsBookingIdRoute
  '/my-bookings': typeof MyBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search-flight': typeof SearchFlightRoute
  '/my-bookings/$bookingId': typeof MyBookingsBookingIdRoute
  '/my-bookings/': typeof MyBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/search-flight'
    | '/my-bookings/$bookingId'
    | '/my-bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/search-flight'
    | '/my-bookings/$bookingId'
    | '/my-bookings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/search-flight'
    | '/my-bookings/$bookingId'
    | '/my-bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchFlightRoute: typeof SearchFlightRoute
  MyBookingsBookingIdRoute: typeof MyBookingsBookingIdRoute
  MyBookingsIndexRoute: typeof MyBookingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search-flight': {
      id: '/search-flight'
      path: '/search-flight'
      fullPath: '/search-flight'
      preLoaderRoute: typeof SearchFlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings/': {
      id: '/my-bookings/'
      path: '/my-bookings'
      fullPath: '/my-bookings/'
      preLoaderRoute: typeof MyBookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings/$bookingId': {
      id: '/my-bookings/$bookingId'
      path: '/my-bookings/$bookingId'
      fullPath: '/my-bookings/$bookingId'
      preLoaderRoute: typeof MyBookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchFlightRoute: SearchFlightRoute,
  MyBookingsBookingIdRoute: MyBookingsBookingIdRoute,
  MyBookingsIndexRoute: MyBookingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
